---
name: openbao

instance_groups:
  - name: openbao
    azs: [z1, z2, z3]
    instances: 3
    persistent_disk: 10240
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: openbao
        release: openbao
        properties:
          openbao:
            port: 443
            ui: false

      - name: bpm
        release: bpm

stemcells:
  - alias: default
    os: ubuntu-jammy
    version: latest

releases:
  - name: openbao
    version: latest

  - name: bpm
    version: latest

update:
  serial: true
  canaries: 0
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 30000-600000
